app/feedback/models.py
from app import db

class Feedback(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100))
    email = db.Column(db.String(100))
    description = db.Column(db.String(300))
    rate = db.Column(db.Integer)
    useful = db.Column(db.Boolean)

app/feedback/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, SelectField, EmailField
from wtforms.validators import DataRequired, Length

class CreateFeedbackForm(FlaskForm):
    name = StringField("Імʼя", validators=[DataRequired("Це поле обовʼязкове"), Length(min=1, max=100)])
    email = EmailField("Пошта", validators=[DataRequired("Це поле обовʼязкове"), Length(min=1, max=100)])
    description = StringField("Опишіть, що ви думаєте", validators=[DataRequired("Це поле обовʼязкове"), Length(min=1, max=300)])
    rate = SelectField("Оцінка", choices=[
        (1, 1), (2, 2), (3, 3), (4, 4), (5, 5),
        (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)
    ])
    submit = SubmitField("Надіслати")

app/feedback/__init__.py
from flask import Blueprint

feedback_blueprint = Blueprint('feedback_bp', __name__, template_folder="templates/feedback")

from . import views

app/feedback/views.py
from flask import flash, render_template, redirect, url_for
from flask_login import login_required

from . import feedback_blueprint
from .forms import CreateFeedbackForm
from .models import db, Feedback

@feedback_blueprint.route("/")
@login_required
def feedback():
    feedback_form = CreateFeedbackForm()
    feedback_list = Feedback.query.all()

    return render_template('feedback.html', feedback_form=feedback_form, feedback_list=feedback_list)

@feedback_blueprint.route("/create_feedback", methods=['POST'])
def create_feedback():
    feedback_form = CreateFeedbackForm()

    if feedback_form.validate_on_submit():
        name = feedback_form.name.data
        email = feedback_form.email.data
        description = feedback_form.description.data
        rate = feedback_form.rate.data

        new_feedback = Feedback(name=name, email=email, description=description, rate=rate, useful=False)

        db.session.add(new_feedback)
        db.session.commit()
        flash("Створення виконано", category=("success"))
        return redirect(url_for("feedback_bp.feedback"))
    
    flash("Помилка при створенні", category=("danger"))
    return redirect(url_for("feedback_bp.feedback"))

@feedback_blueprint.route("/read_feedback/<int:feedback_id>")
def read_feedback(feedback_id=None):
    feedback = Feedback.query.get_or_404(feedback_id)
    return redirect(url_for("feedback"))

@feedback_blueprint.route("/update_feedback/<int:feedback_id>")
def update_feedback(feedback_id=None):
    feedback = Feedback.query.get_or_404(feedback_id)

    feedback.useful = not feedback.useful
    db.session.commit()
    flash("Оновлення виконано", category=("success"))
    return redirect(url_for("feedback"))

@feedback_blueprint.route("/delete_feedback/<int:feedback_id>")
def delete_feedback(feedback_id=None):
    feedback = Feedback.query.get_or_404(feedback_id)

    db.session.delete(feedback)
    db.session.commit()
    flash("Видалення виконано", category=("success"))
    return redirect(url_for("feedback"))

app/feedback/templates/feedback/feedback.html
{% extends 'base.html' %}
{% block title %} Відгуки {% endblock %}

{% block body %}
<section class="page-section" id="feedback_table">
    <!-- Section Heading-->
    <h2 class="page-section-heading text-center text-primary mb-0">Відгуки</h2>
    <!-- Icon Divider-->
    <div class="divider-custom">
        <div class="divider-custom-line"></div>
        <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
        <div class="divider-custom-line"></div>
    </div>
    <div class="row justify-content-center">
        <div class="container col-md-8 col-lg-8">
            <form id="createFeedback" action={{ url_for('feedback_bp.create_feedback') }} method="POST">
                {% from "_render_field.html" import render_field %}
                {{ feedback_form.csrf_token }}
                <div class="form-floating mb-3">
                    {{ render_field(feedback_form.name) }}
                </div>
                <div class="form-floating mb-3">
                    {{ render_field(feedback_form.email) }}
                </div>
                <div class="form-floating mb-3">
                    {{ render_field(feedback_form.description) }}
                </div>
                <div class="form-floating mb-3">
                    {{ render_field(feedback_form.rate) }}
                </div>
                {{feedback_form.submit(class_='btn btn-primary btn-xl')}}
            </form>
        </div>
    </div>
</section>
<section>
    <div class="row justify-content-center">   
        <div class="container col-md-8 col-lg-8">
            <table class="table table-light">
                <thead class="table-primary">
                    <tr class = "feedbackTable">
                        <th class = "feedbackTable">Номер</th>
                        <th class = "feedbackTable">Імʼя</th>
                        <th class = "feedbackTable">Опис</th>
                        <th class = "feedbackTable">Оцінка</th>
                        <th class = "feedbackTable">Корисний?</th>
                        <th class = "feedbackTable">Дії</th>
                    </tr>
                </thead>
                <tbody>
                    {% for feedback in feedback_list %}
                    <tr>
                        <th scope="row">{{ feedback.id }}</th>
                        <td class = "feedbackTable">{{ feedback.title }}</td>
                        <td class = "feedbackTable">{{ feedback.name }}</feedback> }}</td>
                        <td class = "feedbackTable">{{ feedback.description }}</td>
                        <td class = "feedbackTable">{{ feedback.rate }}</td>
                        <td class = "feedbackTable">
                            {% if feedback.useful == False %}
                            <div class="alert alert-secondary" roles="alert">Ні</div>
                            {% else %}
                            <div class="alert alert-success" roles="alert">Так</div>
                            {% endif %}
                        </td>
                        <td>
                            <a class="btn btn-success" href={{url_for("feedback_bp.update_feedback", feedback_id = feedback.id) }}>Оновити</a>
                            <a class="btn btn-danger ms-1" href={{url_for("feedback_bp.delete_feedback", feedback_id = feedback.id) }}>Видалити</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</section>
{% endblock %}