app/todo/models.py
from app import db

class Todo(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100))
    description = db.Column(db.String(200))
    complete = db.Column(db.Boolean)

app/todo/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired, Length

class CreateTodoForm(FlaskForm):
    new_task = StringField("Задача", validators=[DataRequired("Це поле обовʼязкове"), Length(min=1, max=100)])
    description = StringField("Опис", validators=[DataRequired("Це поле обовʼязкове"), Length(min=1, max=200)])
    submit = SubmitField("Створити")

app/todo/__init__.py
from flask import Blueprint

todo_blueprint = Blueprint('todo_bp', __name__, template_folder="templates/todo")

from . import views

app/todo/views.py
from flask import flash, render_template, redirect, url_for
from flask_login import login_required

from . import todo_blueprint
from .forms import CreateTodoForm
from .models import db, Todo

@todo_blueprint.route("/")
@login_required
def todo():
    form = CreateTodoForm()
    todo_list = Todo.query.all()

    return render_template('todo.html', form=form, todo_list=todo_list)

@todo_blueprint.route("/create_todo", methods=['POST'])
def create_todo():
    form = CreateTodoForm()

    if form.validate_on_submit():
        new_task = form.new_task.data
        description = form.description.data
        new_todo = Todo(title=new_task, description=description, complete=False)
        db.session.add(new_todo)
        db.session.commit()
        flash("Створення виконано", category=("success"))
        return redirect(url_for("todo_bp.todo"))
    
    flash("Помилка при створенні", category=("danger"))
    return redirect(url_for("todo_bp.todo"))

@todo_blueprint.route("/read_todo/<int:todo_id>")
def read_todo(todo_id=None):
    todo = Todo.query.get_or_404(todo_id)
    return redirect(url_for("todo_bp.todo"))

@todo_blueprint.route("/update_todo/<int:todo_id>")
def update_todo(todo_id=None):
    todo = Todo.query.get_or_404(todo_id)

    todo.complete = not todo.complete
    db.session.commit()
    flash("Оновлення виконано", category=("success"))
    return redirect(url_for("todo_bp.todo"))

@todo_blueprint.route("/delete_todo/<int:todo_id>")
def delete_todo(todo_id=None):
    todo = Todo.query.get_or_404(todo_id)

    db.session.delete(todo)
    db.session.commit()
    flash("Видалення виконано", category=("success"))
    return redirect(url_for("todo_bp.todo"))

app/todo/templates/todo/todo.html
{% extends 'base.html' %}
{% block title %} База даних {% endblock %}

{% block body %}
<section class="page-section" id="todo_table">
    <!-- Section Heading-->
    <h2 class="page-section-heading text-center text-primary mb-0">База даних ToDo</h2>
    <!-- Icon Divider-->
    <div class="divider-custom">
        <div class="divider-custom-line"></div>
        <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
        <div class="divider-custom-line"></div>
    </div>
    <div class="row justify-content-center">
        <div class="container col-md-8 col-lg-8">
            <form id="createTodo" action={{ url_for('todo_bp.create_todo') }} method="POST">
                {% from "_render_field.html" import render_field %}
                {{ form.csrf_token }}
                <div class="form-floating mb-3">
                    {{ render_field(form.new_task) }}
                </div>
                <div class="form-floating mb-3">
                    {{ render_field(form.description) }}
                </div>
                {{form.submit(class_='btn btn-primary btn-xl')}}
            </form>
        </div>
    </div>
</section>
<section>
    <div class="row justify-content-center">   
        <div class="container col-md-8 col-lg-8">
            <table class="table table-light">
                <thead class="table-primary">
                    <tr class = "todoTable">
                        <th class = "todoTable">Номер</th>
                        <th class = "todoTable">Значення</th>
                        <th class = "todoTable">Опис</th>
                        <th class = "todoTable">Статус</th>
                        <th class = "todoTable">Дії</th>
                    </tr>
                </thead>
                <tbody>
                    {% for todo in todo_list %}
                    <tr>
                        <th scope="row">{{ todo.id }}</th>
                        <td class = "todoTable">{{ todo.title }}</td>
                        <td class = "todoTable">{{ todo.description }}</td>
                        <td class = "todoTable">
                            {% if todo.complete == False %}
                            <div class="alert alert-secondary" roles="alert">В роботі</div>
                            {% else %}
                            <div class="alert alert-success" roles="alert">Виконано</div>
                            {% endif %}
                        </td>
                        <td>
                            <a class="btn btn-success" href={{url_for("todo_bp.update_todo", todo_id = todo.id) }}>Оновити</a>
                            <a class="btn btn-danger ms-1" href={{url_for("todo_bp.delete_todo", todo_id = todo.id) }}>Видалити</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</section>
{% endblock %}